"""empty message

Revision ID: 063502feb244
Revises: a792d667a3ac
Create Date: 2023-08-22 23:47:46.988363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063502feb244'
down_revision = 'a792d667a3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_index('ix_registered_users_first_name')
        batch_op.create_index(batch_op.f('ix_registered_users_first_name'), ['first_name'], unique=False)
        batch_op.drop_index('ix_registered_users_last_name')
        batch_op.create_index(batch_op.f('ix_registered_users_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_users_last_name'))
        batch_op.create_index('ix_registered_users_last_name', ['last_name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_registered_users_first_name'))
        batch_op.create_index('ix_registered_users_first_name', ['first_name'], unique=False)

    # ### end Alembic commands ###
