"""empty message

Revision ID: 17f1d3d35330
Revises: 
Create Date: 2023-08-22 16:22:07.187729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f1d3d35330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_first_name'), ['first_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_last_name'), ['last_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_last_name'))
        batch_op.drop_index(batch_op.f('ix_customer_first_name'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_address'))

    op.drop_table('customer')
    # ### end Alembic commands ###
