"""empty message

Revision ID: a792d667a3ac
Revises: 
Create Date: 2023-08-22 23:35:21.914112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a792d667a3ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)

    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registered_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_registered_users_first_name'), ['first_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_registered_users_last_name'), ['last_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_registered_users_password_hash'), ['password_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_users_password_hash'))
        batch_op.drop_index(batch_op.f('ix_registered_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_registered_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_registered_users_email'))

    op.drop_table('registered_users')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_email'))

    op.drop_table('customer')
    # ### end Alembic commands ###
